import { useEffect, useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { useExperiences, useFamilyProfiles, useHabits, useHealthEntries, useWorkouts } from './hooks'
import { experienceService, familyProfileService, habitService, healthService, v20MeetingService } from './services'
import { supabase } from '../../lib/supabase'
type Tab='habits'|'discipline'|'health'|'family'|'experiences'|'meeting'
const steps=['❤️ Relacionamento','👨‍👩‍👧 Família','💰 Financeiro','🏋️ Saúde','🌎 V20','🎯 Próximo mês']
const stepKeys=['relationship','family','finance','health','v20','next_month']
export function Phase4Root({workspaceId}:{workspaceId:string}){const [tab,setTab]=useState<Tab>('habits'),[create,setCreate]=useState(false),[meeting,setMeeting]=useState<{id:string;current_step:number}|null>(null);const h=useHabits(workspaceId),he=useHealthEntries(workspaceId),w=useWorkouts(workspaceId),f=useFamilyProfiles(workspaceId),e=useExperiences(workspaceId);const list=tab==='habits'?h.data:tab==='health'?[...(he.data??[]),...(w.data??[])]:tab==='family'?f.data:e.data;const start=async()=>{const u=await supabase?.auth.getUser();if(!u?.data.user)return;setMeeting(await v20MeetingService.create({workspace_id:workspaceId,user_id:u.data.user.id,meeting_date:new Date().toISOString().slice(0,10)}) as {id:string;current_step:number})};return <main className="mx-auto min-h-screen max-w-2xl bg-ink p-4 pb-28"><h1 className="text-2xl font-extrabold">V20 • Vida, saúde e família</h1><div className="mt-4 grid grid-cols-3 gap-2">{(['habits','discipline','health','family','experiences','meeting'] as Tab[]).map(x=><button className={`rounded-xl p-3 ${tab===x?'bg-coral':'bg-card'}`} onClick={()=>x==='meeting'&&!meeting?void start():setTab(x)} key={x}>{x==='habits'?'🔥 Hábitos':x==='discipline'?'📊 Disciplina':x==='health'?'🏋️ Saúde':x==='family'?'❤️ Família':x==='experiences'?'🌎 Viver':'💑 Reunião'}</button>)}</div>{tab==='discipline'?<section className="v-card mt-5"><h2 className="text-xl font-bold">Disciplina</h2><b className="text-4xl text-amber">{Math.min(100,(h.data?.length??0)*20+(w.data?.length??0)*10)}%</b><p>Hábitos: {h.data?.length??0} • Treinos: {w.data?.length??0}</p></section>:tab==='meeting'&&meeting?<Wizard meeting={meeting} workspaceId={workspaceId}/>:<section className="mt-5"><button className="v-button mb-3" onClick={()=>setCreate(true)}>+ Criar</button>{(list??[]).map((x:{id:string;title?:string;name?:string;emoji?:string})=><article className="v-card mb-2" key={x.id}>{x.emoji??'•'} <b>{x.title??x.name}</b></article>)}</section>}{create&&<NewEntry tab={tab} workspaceId={workspaceId} close={()=>setCreate(false)}/>}</main>}
function NewEntry({tab,workspaceId,close}:{tab:Tab;workspaceId:string;close:()=>void}){const [title,setTitle]=useState('');const save=async(e:FormEvent)=>{e.preventDefault();const u=await supabase?.auth.getUser();if(!u?.data.user)return;const b={workspace_id:workspaceId,user_id:u.data.user.id,title,emoji:tab==='habits'?'🔥':tab==='health'?'💧':tab==='family'?'❤️':'🌎'};if(tab==='habits')await habitService.create(b);if(tab==='health')await healthService.create({...b,entry_type:'water',value_numeric:250,unit:'ml'});if(tab==='family')await familyProfileService.create({workspace_id:workspaceId,name:title,relationship:'Familiar',created_by_user_id:u.data.user.id});if(tab==='experiences')await experienceService.create({...b,status:'planned'});toast.success('Salvo');close()};return <div className="fixed inset-0 z-50 flex items-end bg-black/70"><form className="w-full rounded-t-3xl bg-surface p-5" onSubmit={save}><input className="v-input" required placeholder="Nome ou título" value={title} onChange={x=>setTitle(x.target.value)}/><button className="v-button mt-4 w-full">Salvar</button><button type="button" className="mt-3 w-full" onClick={close}>Cancelar</button></form></div>}
function Wizard({meeting,workspaceId}:{meeting:{id:string;current_step:number};workspaceId:string}){const [n,setN]=useState(meeting.current_step||1),[text,setText]=useState(''),[saving,setSaving]=useState(false);useEffect(()=>{const t=setTimeout(()=>{if(text){setSaving(true);void v20MeetingService.saveStep(meeting.id,workspaceId,stepKeys[n-1],n,{notes:text}).finally(()=>setSaving(false))}},700);return()=>clearTimeout(t)},[text,n,meeting.id,workspaceId]);return <section className="v-card mt-5"><p>Passo {n} de 6 • {saving?'Salvando…':'Salvo ✓'}</p><h2 className="mt-3 text-xl font-bold">{steps[n-1]}</h2><textarea className="v-input mt-4 min-h-36" value={text} onChange={x=>setText(x.target.value)} placeholder="Registre os pontos e decisões"/><button className="v-button mt-4 w-full" onClick={()=>n===6?void v20MeetingService.complete(meeting.id).then(()=>toast.success('Reunião concluída')):setN(n+1)}>{n===6?'Concluir reunião':'Salvar e continuar →'}</button></section>}
