create type public.goal_horizon as enum ('life','ten_year','five_year','two_year','year','quarter','month','week');
create type public.goal_status as enum ('planned','in_progress','completed','paused','cancelled');
create type public.goal_progress_method as enum ('manual','value','tasks','subgoals');
create type public.roadmap_status as enum ('planned','in_progress','completed','paused');

create table public.vision_items (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references public.profiles(id), category_id uuid references public.categories(id) on delete set null,
 title text not null check(char_length(title) between 1 and 160), description text, emoji text not null default '🌅', color text not null default '#FF6B57' check(color ~ '^#[0-9A-Fa-f]{6}$'), image_url text, position integer not null default 0, is_active boolean not null default true, is_archived boolean not null default false, visibility public.visibility_scope not null default 'private', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.roadmap_milestones (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references public.profiles(id), title text not null check(char_length(title) between 1 and 160), description text, emoji text not null default '💡', color text not null default '#FF6B57' check(color ~ '^#[0-9A-Fa-f]{6}$'), target_date date not null, status public.roadmap_status not null default 'planned', progress numeric(5,2) not null default 0 check(progress between 0 and 100), position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.goals (
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references public.profiles(id), parent_id uuid references public.goals(id) on delete restrict, vision_item_id uuid references public.vision_items(id) on delete set null, category_id uuid references public.categories(id) on delete set null,
 title text not null check(char_length(title) between 1 and 200), description text, emoji text not null default '🎯', color text not null default '#FF6B57' check(color ~ '^#[0-9A-Fa-f]{6}$'), horizon public.goal_horizon not null default 'year', status public.goal_status not null default 'planned', progress_method public.goal_progress_method not null default 'manual', manual_progress numeric(5,2) not null default 0 check(manual_progress between 0 and 100), initial_value numeric(14,2), current_value numeric(14,2), target_value numeric(14,2), direction text not null default 'increase' check(direction in ('increase','decrease')), target_date date, priority smallint not null default 3 check(priority between 1 and 5), is_weekly_focus boolean not null default false, visibility public.visibility_scope not null default 'private', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz, archived_at timestamptz, deleted_at timestamptz
);
create table public.roadmap_milestone_goals (milestone_id uuid not null references public.roadmap_milestones(id) on delete cascade, goal_id uuid not null references public.goals(id) on delete cascade, primary key(milestone_id,goal_id));
create table public.daily_priorities (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references public.profiles(id), date date not null default current_date, slot text not null check(slot in ('money','business','life')), task_id uuid references public.tasks(id) on delete set null, title text not null, emoji text not null default '🔥', color text not null default '#FF6B57', is_completed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,date,slot));
alter table public.tasks add column goal_id uuid references public.goals(id) on delete set null, add column scheduled_date date, add column duration_minutes integer check(duration_minutes > 0), add column recurrence_rule text;
create index goals_workspace_active_idx on public.goals(workspace_id, target_date) where deleted_at is null;
create index tasks_workspace_today_idx on public.tasks(workspace_id, scheduled_date) where deleted_at is null;
create trigger vision_updated before update on public.vision_items for each row execute procedure public.set_updated_at(); create trigger roadmap_updated before update on public.roadmap_milestones for each row execute procedure public.set_updated_at(); create trigger goals_updated before update on public.goals for each row execute procedure public.set_updated_at(); create trigger priorities_updated before update on public.daily_priorities for each row execute procedure public.set_updated_at();
alter table public.vision_items enable row level security; alter table public.roadmap_milestones enable row level security; alter table public.goals enable row level security; alter table public.roadmap_milestone_goals enable row level security; alter table public.daily_priorities enable row level security;
grant select,insert,update,delete on public.vision_items,public.roadmap_milestones,public.goals,public.roadmap_milestone_goals,public.daily_priorities to authenticated;
create policy "vision_read" on public.vision_items for select to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=workspace_id and m.user_id=(select auth.uid())));
create policy "vision_write" on public.vision_items for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()) and exists(select 1 from public.workspace_members m where m.workspace_id=workspace_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin','member')));
create policy "roadmap_read" on public.roadmap_milestones for select to authenticated using(exists(select 1 from public.workspace_members m where m.workspace_id=workspace_id and m.user_id=(select auth.uid())));
create policy "roadmap_write" on public.roadmap_milestones for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()) and exists(select 1 from public.workspace_members m where m.workspace_id=workspace_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin','member')));
create policy "goals_read" on public.goals for select to authenticated using(user_id=(select auth.uid()) or (visibility='workspace' and exists(select 1 from public.workspace_members m where m.workspace_id=workspace_id and m.user_id=(select auth.uid()))));
create policy "goals_write" on public.goals for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()) and exists(select 1 from public.workspace_members m where m.workspace_id=workspace_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin','member')));
create policy "junction_read" on public.roadmap_milestone_goals for select to authenticated using(exists(select 1 from public.roadmap_milestones r join public.workspace_members m on m.workspace_id=r.workspace_id where r.id=milestone_id and m.user_id=(select auth.uid())));
create policy "junction_write" on public.roadmap_milestone_goals for all to authenticated using(exists(select 1 from public.roadmap_milestones r where r.id=milestone_id and r.user_id=(select auth.uid()))) with check(exists(select 1 from public.roadmap_milestones r where r.id=milestone_id and r.user_id=(select auth.uid())));
create policy "priority_read" on public.daily_priorities for select to authenticated using(user_id=(select auth.uid()));
create policy "priority_write" on public.daily_priorities for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()) and exists(select 1 from public.workspace_members m where m.workspace_id=workspace_id and m.user_id=(select auth.uid()) and m.role in ('owner','admin','member')));
